version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - mysql_data:/var/lib/mysql     
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
###########################################################################################
  backend:
    build:
      context: ./backend  
      dockerfile: dockerfile.dev
    container_name: backend
    env_file:
      - .env.dev 
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy 
    networks:
      - backend-network
###########################################################################################
  frontend:
    build:
      context: ./frontend  
      dockerfile: dockerfile.dev 
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app  
      - /usr/src/app/node_modules  
    ports:
      - "3000:3000"  
    networks:
      - backend-network
    environment:
      - CHOKIDAR_USEPOLLING=true 
###########################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"  
    networks:
      - backend-network
###########################################################################################
networks:
  backend-network:
    driver: bridge
###########################################################################################
volumes:
  mysql_data: